name: "Dev Pipeline"
on:
  # Manual trigger
  workflow_dispatch:
  push:
    paths:
      - '*/**'
  pull_request:
    branches: [release/* ]
defaults:
  run:
    shell: bash
jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  deploy-dev:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
    secrets: inherit


